### ISSUE TITLE
query returns all fields instead of only select array fields

### ISSUE THREAD

**Issue by DevinStetler** [chris48s/cakephp-geodistance#2]
$query = $myTable
    ->find('bydistance', $options)
    ->select(['address', 'lat', 'lng']);

is returning fields like this:
distance, address, lat, lng, column A, column B, column C, ....

In other words, it places distance as first field, then fields chosen in select(), then all remaining fields in table order.

I expect this to only return the fields in the select array ['address', 'lat', 'lng'], as well as the distance.

**Comment by chris48s** [comment]
Hi @DevinStetler Thanks for reporting this.
this is fixed in ecd0822 . I've just pushed a new version to packagist which includes this fix: https://packagist.org/packages/chris48s/cakephp-geodistance#1.1.0
Upgrade your dependency to 1.1.0 and you should be sorted. Ta

**Comment by DevinStetler** [comment]
Brilliant!! Thanks so much! Beautifully simple plugin, very effective.
