### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by abbeenorris** [chris48s/cakephp-geodistance#3]
Hi, 

Having this error on my database whilst at the configuration stage:

"syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'"

Not sure why I am having this problem, if you could help that would be great. 

Thanks

Abbie

**Comment by chris48s** [comment]
Somewhere in your code there is a syntax error, probably somewhere you're defining an array.

I suspect it is unrelated to this package, but if you can provide a reproducible test case (i.e: some example code I can use to cause this same behaviour so I can debug it), I'll have a look at it.

**Comment by abbeenorris** [comment]
Thanks for getting back to me so quickly. 

I have attached the file I am working on, if you could have a quick look that would be fantastic. I think it is a case of i've been looking at the code for so long i've become blind to the error. Many Thanks. 

<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Shelters Model
 *
 * @property \App\Model\Table\AnimalsTable|\Cake\ORM\Association\HasMany $Animals
 *
 * @method \App\Model\Entity\Shelter get($primaryKey, $options = [])
 * @method \App\Model\Entity\Shelter newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Shelter[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Shelter|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Shelter patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Shelter[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Shelter findOrCreate($search, callable $callback = null, $options = [])
 */

class MyTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->addBehavior('Chris48s/GeoDistance.GeoDistance' [
            'latitudeColumn' => 'lat',
            'longitudeColumn' => 'lng',
            'units' => 'km'
        ]);
    }
}

class SheltersTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('shelters');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->hasMany('Animals', [
            'foreignKey' => 'shelters_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 32)
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        $validator
            ->numeric('Lat')
            ->requirePresence('Lat', 'create')
            ->notEmpty('Lat');

        $validator
            ->numeric('Lng')
            ->requirePresence('Lng', 'create')
            ->notEmpty('Lng');

        return $validator;
    }
}

**Comment by abbeenorris** [comment]
Thanks for getting back to me so quickly.

I have attached the file I am working on, if you could have a quick look that would be fantastic. I think it is a case of i've been looking at the code for so long i've become blind to the error. Many Thanks.

[SheltersTable.docx](https://github.com/chris48s/cakephp-geodistance/files/1923479/SheltersTable.docx)

**Comment by chris48s** [comment]
There's a missing comma:

```php
$this->addBehavior('Chris48s/GeoDistance.GeoDistance' [
    'latitudeColumn' => 'lat',
    'longitudeColumn' => 'lng',
    'units' => 'km'
]);
```

should be

```php
$this->addBehavior('Chris48s/GeoDistance.GeoDistance', [
    'latitudeColumn' => 'lat',
    'longitudeColumn' => 'lng',
    'units' => 'km'
]);
```

I see you've copied that from an example in the docs. My bad :man_facepalming: I've [updated the example](https://github.com/chris48s/cakephp-geodistance/commit/f91a37eda2afe1d7de7f4906e3351358b7223a69)

**Comment by abbeenorris** [comment]
Thank you so much!
